version: '3.0'

services:

  backend:
    build: ./Backend
    container_name: jobquest_backendcontainer
    image: jobquest_backendimage
    env_file:
      - ./Backend/.env
    ports:
      - 8000:8000


  frontend:
    build: ./Frontend
    container_name: jobquest_frontendcontainer
    image: jobquest_frontendimage
    env_file:
      - ./Frontend/.env
    ports:
      - 5173:5173
    depends_on:
      - backend


  celeryworker:
    build: ./Backend
    container_name: jobquest_celeryworker
    env_file:
      - ./Backend/.env
    command: celery -A celery_worker worker --concurrency=2 --loglevel=debug --without-mingle --without-gossip --without-heartbeat -P eventlet
    depends_on:
      - rabbitmq
      - db

  rabbitmq:
    container_name: jobquest_rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  db:
    container_name: jobquest_db
    image: postgres:14
    env_file:
      - ./Backend/.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_USERNAME}
      POSTGRES_USERNAME: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_HOST_AUTH_METHOD: trust
      


volumes:
  postgres_data:
