name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest


    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout to the repo
        uses: actions/checkout@v2


      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v1


      - name: Set up env files
        run: |
          mkdir -p Frontend Backend/JobService
          echo "VITE_BACKEND_URL=${VITE_BACKEND_URL}" > Frontend/.env
          echo "VITE_WEBSOCKET_BACKEND_URL=${VITE_WEBSOCKET_BACKEND_URL}" >> Frontend/.env
          echo "FRONTEND_URL=${FRONTEND_URL}" > Backend/JobService/.env
          echo "DATABASE_URL=${DATABASE_URL}" >> Backend/JobService/.env
          echo "DATABASE_USERNAME=${DATABASE_USERNAME}" >> Backend/JobService/.env
          echo "DATABASE_PASSWORD=${DATABASE_PASSWORD}" >> Backend/JobService/.env
          echo "CELERY_BROKER=${CELERY_BROKER}" >> Backend/JobService/.env

      - name: Build Docker images
        run: |
          docker compose build --no-cache

      - name: Run Docker Compose
        run: |
          docker compose up -d

      - name: Wait for services to start
        run: sleep 20

      - name: Stop and remove containers
        run: |
          docker compose down