name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: ubuntu-latest


    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker images
        env:
          FRONTEND_URL: http://localhost:5173
          DATABASE_URL: db/postgres
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres
          CELERY_BROKER: amqp://guest:guest@rabbitmq:5672/
        run: |
          docker-compose build

      - name: Run Docker Compose
        run: |
          docker-compose up
